config/routes.rb
Rails.application.routes.draw do


  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root         to: 'home#index'
    get 'index', to: 'home#index'
    resources :products,   only: [:index, :show], param: :slug_or_id
    resources :categories, only: [:show]

    get '/sample',                  to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  scope :list_of_colors, -> { find_by(presentation: 'Color').option_values }
  scope :list_of_size,   -> { find_by(presentation: 'Size').option_values }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :display_includes, -> { includes(master: [:images, :default_price]) }
  scope :order_by_recent,  -> { order(available_on: :desc) }
  scope :released,         -> { where('available_on < ?', Time.zone.now) }

  scope :related_products, lambda { |product|
    joins(:taxons).where(spree_taxons: { id: product.taxon_ids })
                  .where.not(id: product.id).distinct
  }

  def self.master_variants
    ids = all.pluck(:id)
    Spree::Variant.master_variants.where(product_id: ids)
  end

  def self.take_random(number)
    ids = all.pluck(:id).sample(number)
    where(id: ids)
  end
end

app/models/spree/taxonomy_decorator.rb
Spree::Taxonomy.class_eval do
  scope :category_root, -> { find_by(name: 'Categories').root }
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  scope :master_variants,  -> { where(is_master: true) }
  scope :display_includes, -> { includes([product: { master: :default_price}], :images) }

  scope :order_by_dateASC,   -> { joins(:product).order('spree_products.available_on')}
  scope :order_by_dateDESC,  -> { joins(:product).order('spree_products.available_on desc')}
  scope :order_by_priceASC,  -> { joins(:default_price).order('spree_prices.amount')}
  scope :order_by_priceDESC, -> { joins(:default_price).order('spree_prices.amount desc')}

  def self.order_by(sort = 'dateDESC')
    sort = 'dateDESC' if sort.blank?
    try("order_by_#{sort}")
  end

  def self.in_category(taxon)
    joins(product: :taxons)
      .where(spree_taxons: { id: taxon.self_and_descendants.pluck(:id) })
      .master_variants
  end

  def self.search_by_options(*values)
    option_values = Spree::OptionValue.where(presentation: values)
    if option_values.blank?
      master_variants
    else
      option_values.inject(all) do |variants, option_value|
        variants.where(id: option_value.variants.pluck(:id))
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController

  def show
    @taxonomy = Spree::Taxonomy.category_root
    @taxon = Spree::Taxon.find(params[:id])
    @products = Spree::Variant.in_category(@taxon)
                              .display_includes
                              .order_by(params[:sort])
    @options = Spree::OptionType.all
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  DISPLAY_NUM = 6

  def index
    @new_products = Spree::Product.released
                                  .display_includes
                                  .order_by_recent.limit(DISPLAY_NUM)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController

  def index
    @taxonomy = Spree::Taxonomy.category_root
    @products = Spree::Variant.display_includes
                              .search_by_options(params[:color], params[:size])
                              .order_by(params[:sort])
    @options = Spree::OptionType.all
  end

  def show
    @product = Spree::Product.friendly.find(params[:slug_or_id])
    @related_products = Spree::Product.related_products(@product)
                                      .display_includes
                                      .take_random(4)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout 'sample'

  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページタイトルの設定
  def full_title(page_title='')
    base_title = 'BIGBAG Store'
    if page_title.empty?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end

  def display_of_option_type_and_value
    option_values =
      Spree::OptionValue.where(presentation: [params[:color], params[:size]])
    if option_values.blank?
      'All PRODUCTS'
    else
      option_values.inject([]) do |array, option_value|
        array << "#{option_value.option_type.presentation} : #{option_value.presentation}"
      end.join(' ')
    end
  end
end

app/views/layouts/_copy_right.html.erb
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li><a href="#">Barbour </a></li>
            <li><a href="#">Brioni </a></li>
            <li><a href="#">Oliver Spencer</a></li>
            <li><a href="#">Belstaff</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">

  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html"><%= image_tag("img/logo.png", :alt => "") %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="index.html">Home</a></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</b></a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li class="active"><a href="single_product.html">Single Product</a></li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="about_us.html">About Us</a></li>
              <li><a href="signup.html">Register</a></li>
              <li><a href="signup-login.html">Register or Login</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="lost-password.html">Password Recovery</a></li>
              <li><a href="privacy_policy.html">Privacy Policy</a></li>
              <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
              <li><a href="404.html">404 Not Found</a></li>
              <li><a href="coming-soon.html">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="account-dashboard.html">Dashboard</a></li>
              <li><a href="account-profile.html">Profile</a></li>
              <li><a href="account-all-orders.html">All Orders</a></li>
              <li><a href="account-single-order.html">Single Order</a></li>
              <li><a href="account-wishlist.html">Wishlist</a></li>
              <li><a href="account-address.html">Address</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

</div>

app/views/layouts/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= label %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active"><%= label %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_login_modal.html.erb
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_partners_slider.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="owl-carousel partnersLogoSlider">
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]> <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> <![endif]-->

app/views/layouts/_signup_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>
</head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/copy_right' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render 'layouts/light_section', label: @product.name %>
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <%= render 'thumbnails' %>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <a href="<%= potepan_products_path %>"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a>
              </li>
              <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
            </ul>
            <%= render 'cart_form' %>
            <%= render 'properties' %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'related_products' %>
  </div>
</section>

app/views/potepan/shared/_product_categories.html.erb
<div class="panel-heading">商品カテゴリー</div>
<div class="panel-body">
  <ul class="list-unstyled">
  <% object.each do |category| %>
    <li>
    <% unless category.leaf? %>
      <a><%= category.name %></a>
      <ul class="children" style="margin-left:10px">
      <% category.children.each do |child| %>
        <li>
          <%= link_to potepan_category_path(child.id) do %>
            <%= child.name %><span><%= "(#{child.products.count})" %></span>
          <% end %>
        </li>
      <% end %>
      </ul>
    <% else %>
      <%= link_to potepan_category_path(category.id) do %>
        <%= category.name %><span><%= "(#{category.products.count})" %></span>
      <% end %>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/potepan/shared/_product_list_layout.html.erb
<div class="col-xs-12">
  <div class="media">
    <div class="media-left">
      <%= image_tag(product.display_image.attachment.url, :class => "media-object", :alt => "Image") %>
      <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to product.name, potepan_product_path(product) %></h4>
      <p><%= product.description %></p>
      <h3><%= product.display_price %></h3>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
        <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
      </div>
    </div>
  </div>
</div>

app/views/potepan/shared/product/_product_caption.html.erb
<div class="productCaption clearfix">
  <%= link_to potepan_product_path(product) do %>
    <h5><%= product.name %></h5>
  <% end %>
  <h3><%= product.display_price %></h3>
</div>

app/views/potepan/shared/sidebar/_search_by_category_sidebar.html.erb
<div class="panel-heading">商品カテゴリー</div>
<div class="panel-body">
  <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
    <ul class="nav navbar-nav side-nav">
      <% object.children.each do |category| %>
        <% if category.leaf? %>
        <li>
          <%= link_to potepan_category_path(category.id) do %>
            <i class="fa fa-caret-right" aria-hidden="true"></i>
            <%= category.name %> <span>(<%= category.products.count %>)</span>
          <% end %>
        </li>
        <% else %>
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#<%= category.name %>"><%= category.name %><i class="fa fa-plus"></i></a>
          <ul id="<%= category.name %>" class="collapse <%= 'in' if category.child_ids.include?(params[:id].to_i) %> collapseItem">
          <% category.children.each do |child_category| %>
            <li>
              <a href="<%= potepan_category_path(child_category.id) %>">
                <i class="fa fa-caret-right" aria-hidden="true"></i>
                <%= child_category.name %> <span>(<%= child_category.products.count %>)</span>
              </a>
            </li>
          <% end %>
          </ul>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/shared/sidebar/_search_by_color_sidebar.html.erb
<div class="panel-heading">色から探す</div>
<div class="panel-body">
  <ul class="list-unstyled">
  <% options.list_of_colors.each do |option| %>
    <li>
    <%= link_to potepan_products_path(color: option.name) do %>
      <%= option.name %><span>(<%= option.variants.count %>)</span>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/potepan/shared/sidebar/_search_by_size_sidebar.html.erb
<div class="panel-heading">サイズから探す</div>
<div class="panel-body">
  <ul class="list-unstyled clearfix">
  <% options.list_of_size.each do |option| %>
    <li>
    <%= link_to potepan_products_path(size: option.presentation) do %>
      <%= option.name %><span>(<%= option.variants.count %>)</span>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>